"""initial schema

Revision ID: 2bc06fa16cbd
Revises: None
Create Date: 2026-06-05 02:55:16.780169+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Revision identifiers used by Alembic.
revision: str = "2bc06fa16cbd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "client",
                "fitness_trainer",
                "nutritionist",
                "master_coach",
                "super_admin",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "idx_users_active",
        "users",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "body_metrics",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_by", sa.UUID(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("body_fat_pct", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("muscle_mass_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "weight_kg IS NOT NULL OR body_fat_pct IS NOT NULL OR muscle_mass_kg IS NOT NULL",
            name="chk_at_least_one_metric",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_body_metrics_user_time",
        "body_metrics",
        ["user_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "client_staff_assignments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.Column(
            "staff_role",
            sa.Enum(
                "fitness_trainer",
                "nutritionist",
                "master_coach",
                name="staff_role_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_reason", sa.String(length=100), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_assignments_client",
        "client_staff_assignments",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "idx_assignments_staff_active",
        "client_staff_assignments",
        ["staff_id"],
        unique=False,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_index(
        "uq_one_active_master_coach",
        "client_staff_assignments",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'master_coach'"),
    )
    op.create_index(
        "uq_one_active_nutritionist",
        "client_staff_assignments",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'nutritionist'"),
    )
    op.create_index(
        "uq_one_active_trainer",
        "client_staff_assignments",
        ["client_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'fitness_trainer'"),
    )
    op.create_table(
        "diet_plans",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_personal", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_template", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_modified_by", sa.UUID(), nullable=True),
        sa.Column("last_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_diet_plans_owner", "diet_plans", ["owner_id"], unique=False)
    op.create_index(
        "uq_one_active_diet_plan",
        "diet_plans",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true AND is_template = false"),
    )
    op.create_table(
        "intake_profiles",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column(
            "fitness_goal",
            sa.Enum(
                "weight_loss",
                "muscle_gain",
                "endurance",
                "body_recomposition",
                "general_health",
                name="fitness_goal_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="experience_level_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "injuries",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "equipment",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("dietary_notes", sa.Text(), nullable=True),
        sa.Column("target_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("current_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_table(
        "plan_activity_log",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "plan_type",
            sa.Enum("workout", "diet", name="plan_type_enum"),
            nullable=False,
        ),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "created",
                "updated",
                "entry_added",
                "entry_removed",
                "entry_updated",
                "commented",
                "activated",
                "deactivated",
                "override_applied",
                name="activity_action_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "log_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activity_log_actor",
        "plan_activity_log",
        ["actor_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "idx_activity_log_plan",
        "plan_activity_log",
        ["plan_type", "plan_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "plan_comments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "plan_type",
            sa.Enum("workout", "diet", name="plan_type_enum"),
            nullable=False,
        ),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_plan_comments_lookup",
        "plan_comments",
        ["plan_type", "plan_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "plan_versions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "plan_type",
            sa.Enum("workout", "diet", name="plan_type_enum"),
            nullable=False,
        ),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("modified_by", sa.UUID(), nullable=False),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_plan_versions_lookup",
        "plan_versions",
        ["plan_type", "plan_id", "modified_at"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_id"),
    )
    op.create_index(
        "idx_rt_active",
        "refresh_tokens",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("is_revoked = false"),
    )
    op.create_index("idx_rt_token_id", "refresh_tokens", ["token_id"], unique=False)
    op.create_index("idx_rt_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "workout_programs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_personal", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_template", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_modified_by", sa.UUID(), nullable=True),
        sa.Column("last_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workout_programs_owner", "workout_programs", ["owner_id"], unique=False
    )
    op.create_index(
        "uq_one_active_workout_program",
        "workout_programs",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true AND is_template = false"),
    )
    op.create_table(
        "diet_entries",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("food_name", sa.String(length=255), nullable=False),
        sa.Column("calories", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fat_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("carbs_g", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("calories >= 0", name="chk_calories_non_negative"),
        sa.CheckConstraint("carbs_g >= 0", name="chk_carbs_non_negative"),
        sa.CheckConstraint("fat_g >= 0", name="chk_fat_non_negative"),
        sa.CheckConstraint("protein_g >= 0", name="chk_protein_non_negative"),
        sa.ForeignKeyConstraint(["plan_id"], ["diet_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_diet_entries_plan_ord",
        "diet_entries",
        ["plan_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "program_weeks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("week_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "label",
            sa.String(length=100),
            server_default=sa.text("'Week'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["workout_programs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_program_weeks_ord",
        "program_weeks",
        ["program_id", "week_number"],
        unique=False,
    )
    op.create_index(
        "uq_program_week", "program_weeks", ["program_id", "week_number"], unique=True
    )
    op.create_table(
        "program_days",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("week_id", sa.UUID(), nullable=False),
        sa.Column("day_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "label",
            sa.String(length=100),
            server_default=sa.text("'Day'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["week_id"], ["program_weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_program_days_ord", "program_days", ["week_id", "day_number"], unique=False
    )
    op.create_index(
        "uq_week_day", "program_days", ["week_id", "day_number"], unique=True
    )
    op.create_table(
        "workout_prescriptions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("day_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.SmallInteger(), nullable=False),
        sa.Column("exercise_name", sa.String(length=255), nullable=False),
        sa.Column("warmup_sets", sa.SmallInteger(), nullable=True),
        sa.Column("working_sets", sa.SmallInteger(), nullable=True),
        sa.Column("reps_min", sa.SmallInteger(), nullable=True),
        sa.Column("reps_max", sa.SmallInteger(), nullable=True),
        sa.Column("reps_note", sa.String(length=255), nullable=True),
        sa.Column(
            "prescribed_load_kg", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("prescribed_load_text", sa.String(length=100), nullable=True),
        sa.Column("prescribed_rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("prescribed_rir", sa.SmallInteger(), nullable=True),
        sa.Column("rest_seconds", sa.SmallInteger(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reps_min IS NOT NULL OR reps_note IS NOT NULL", name="chk_reps_defined"
        ),
        sa.ForeignKeyConstraint(["day_id"], ["program_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_prescriptions_day_ord",
        "workout_prescriptions",
        ["day_id", "order_index"],
        unique=False,
    )
    op.create_index(
        "uq_day_exercise_order",
        "workout_prescriptions",
        ["day_id", "order_index"],
        unique=True,
    )
    op.create_table(
        "workout_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("prescription_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("exercise_name", sa.String(length=255), nullable=True),
        sa.Column(
            "logged_at",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("actual_sets", sa.SmallInteger(), nullable=False),
        sa.Column("actual_reps", sa.SmallInteger(), nullable=False),
        sa.Column("actual_load_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("actual_rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("readiness", sa.SmallInteger(), nullable=True),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=True),
        sa.Column("client_notes", sa.Text(), nullable=True),
        sa.Column(
            "tonnage_kg",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "CASE WHEN actual_load_kg IS NOT NULL THEN CAST(actual_sets AS NUMERIC) * actual_reps * actual_load_kg ELSE NULL END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("video_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "video_source",
            sa.Enum("external_link", "upload", name="video_source_enum"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prescription_id IS NOT NULL OR exercise_name IS NOT NULL",
            name="chk_exercise_reference",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"], ["workout_prescriptions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workout_logs_client_date",
        "workout_logs",
        ["client_id", "logged_at"],
        unique=False,
    )
    op.create_index(
        "idx_workout_logs_prescription",
        "workout_logs",
        ["prescription_id"],
        unique=False,
        postgresql_where=sa.text("prescription_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_workout_logs_prescription",
        table_name="workout_logs",
        postgresql_where=sa.text("prescription_id IS NOT NULL"),
    )
    op.drop_index("idx_workout_logs_client_date", table_name="workout_logs")
    op.drop_table("workout_logs")
    op.drop_index("uq_day_exercise_order", table_name="workout_prescriptions")
    op.drop_index("idx_prescriptions_day_ord", table_name="workout_prescriptions")
    op.drop_table("workout_prescriptions")
    op.drop_index("uq_week_day", table_name="program_days")
    op.drop_index("idx_program_days_ord", table_name="program_days")
    op.drop_table("program_days")
    op.drop_index("uq_program_week", table_name="program_weeks")
    op.drop_index("idx_program_weeks_ord", table_name="program_weeks")
    op.drop_table("program_weeks")
    op.drop_index("idx_diet_entries_plan_ord", table_name="diet_entries")
    op.drop_table("diet_entries")
    op.drop_index(
        "uq_one_active_workout_program",
        table_name="workout_programs",
        postgresql_where=sa.text("is_active = true AND is_template = false"),
    )
    op.drop_index("idx_workout_programs_owner", table_name="workout_programs")
    op.drop_table("workout_programs")
    op.drop_index("idx_rt_user_id", table_name="refresh_tokens")
    op.drop_index("idx_rt_token_id", table_name="refresh_tokens")
    op.drop_index(
        "idx_rt_active",
        table_name="refresh_tokens",
        postgresql_where=sa.text("is_revoked = false"),
    )
    op.drop_table("refresh_tokens")
    op.drop_index("idx_plan_versions_lookup", table_name="plan_versions")
    op.drop_table("plan_versions")
    op.drop_index(
        "idx_plan_comments_lookup",
        table_name="plan_comments",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_table("plan_comments")
    op.drop_index("idx_activity_log_plan", table_name="plan_activity_log")
    op.drop_index("idx_activity_log_actor", table_name="plan_activity_log")
    op.drop_table("plan_activity_log")
    op.drop_table("intake_profiles")
    op.drop_index(
        "uq_one_active_diet_plan",
        table_name="diet_plans",
        postgresql_where=sa.text("is_active = true AND is_template = false"),
    )
    op.drop_index("idx_diet_plans_owner", table_name="diet_plans")
    op.drop_table("diet_plans")
    op.drop_index(
        "uq_one_active_trainer",
        table_name="client_staff_assignments",
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'fitness_trainer'"),
    )
    op.drop_index(
        "uq_one_active_nutritionist",
        table_name="client_staff_assignments",
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'nutritionist'"),
    )
    op.drop_index(
        "uq_one_active_master_coach",
        table_name="client_staff_assignments",
        postgresql_where=sa.text("ended_at IS NULL AND staff_role = 'master_coach'"),
    )
    op.drop_index(
        "idx_assignments_staff_active",
        table_name="client_staff_assignments",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index("idx_assignments_client", table_name="client_staff_assignments")
    op.drop_table("client_staff_assignments")
    op.drop_index("idx_body_metrics_user_time", table_name="body_metrics")
    op.drop_table("body_metrics")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index(
        "idx_users_active",
        table_name="users",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS activity_action_enum")
    op.execute("DROP TYPE IF EXISTS video_source_enum")
    op.execute("DROP TYPE IF EXISTS plan_type_enum")
    op.execute("DROP TYPE IF EXISTS experience_level_enum")
    op.execute("DROP TYPE IF EXISTS fitness_goal_enum")
    op.execute("DROP TYPE IF EXISTS staff_role_enum")
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
