"""
CoachingInvite domain entity.

Design choice — invite as a domain entity, not just a DB record:
    The invite has a lifecycle (valid → used / expired / revoked) with
    business rules: it can only be accepted once, only before expiry,
    and only by someone who isn't the staff member who created it.
    These rules belong in the domain, not in a route handler.

Design choice — code generation uses secrets.choice (cryptographic RNG):
    Invite codes must not be guessable. random.choice() is seeded by time
    and predictable. secrets.choice() uses the OS CSPRNG and is safe for
    security-sensitive token generation.

Design choice — alphabet excludes O, 0, I, 1:
    These four characters are visually ambiguous across fonts and
    handwriting. A client misreading "0" as "O" or "1" as "I" would get
    a frustrating "code not found" error. The 30-character alphabet still
    provides 729,000,000 possible 6-character codes — far more than needed.
"""

import secrets
from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

from domain.entities.enums import StaffRole

# Unambiguous uppercase alphabet — no O/0 or I/1
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def generate_invite_code() -> str:
    """
    Generate a random 7-character invite code in XXX-XXX format.
    Example: "QRT-K4P", "AHN-7WD"

    Uses the OS CSPRNG via secrets.choice — safe for security-sensitive tokens.
    """
    part1 = "".join(secrets.choice(_CODE_ALPHABET) for _ in range(3))
    part2 = "".join(secrets.choice(_CODE_ALPHABET) for _ in range(3))
    return f"{part1}-{part2}"


@dataclass(frozen=True)
class CoachingInvite:
    """
    A time-limited, single-use invite code generated by a coaching staff
    member for a specific client to accept.

    Maps to the `coaching_invites` table.

    Lifecycle:
        created  → is_valid=True
        accepted → is_used=True, used_at/used_by populated
        expired  → is_expired=True (no mutation needed — time-based)
        revoked  → row deleted (hard delete; unused invites have no history value)
    """
    id:         UUID
    staff_id:   UUID
    staff_role: StaffRole
    code:       str             # "QRT-K4P" — always stored uppercase
    expires_at: datetime
    used_at:    datetime | None
    used_by:    UUID | None     # client_id who accepted
    created_at: datetime

    @property
    def is_expired(self) -> bool:
        from datetime import timezone
        return self.expires_at <= datetime.now(tz=timezone.utc)

    @property
    def is_used(self) -> bool:
        return self.used_at is not None

    @property
    def is_valid(self) -> bool:
        """True only when the code can still be accepted by a client."""
        return not self.is_expired and not self.is_used